# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: tr7zw
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Berlin
          
          # Plugins
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_ignored: CSS, HTML, PHP, Hack
          plugin_languages_limit: 8
          plugin_languages_threshold: 2%
          plugin_calendar: yes
          plugin_calendar_limit: 5
      - uses: lowlighter/metrics@latest
        with:
          filename: rightside.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: xmoderlive
          template: classic
          base: metadata
          config_timezone: India
